name: ci-only

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Initial Setup
        run: |
          sudo apt-get -qy install jq
      - name: Validate Images
        run: |
          jq empty functions.json
          jq empty templates.json
