name: validate

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Initial Setup
        run: |
          sudo apt-get -qy install jq
      - uses: alexellis/arkade-get@master
        with:
          crane: latest
      - name: Validate Images
        run: |
          jq empty functions.json
          jq empty templates.json
      - name: Validate functions in store
        run: |
          ./ci/check_store_functions.sh
